### ISSUE TITLE
Requests to document-server via https do not work in version 1.1.0

### ISSUE THREAD

**Issue by iamwildtuna** [ONLYOFFICE/onlyoffice-redmine#21]
Now CallbackHelper sends only HTTP requests even to https addresses https://github.com/ONLYOFFICE/onlyoffice-redmine/blob/main/app/models/callback_helper.rb#L77. I see this bug is already fixed in the [revision](https://github.com/ONLYOFFICE/onlyoffice-redmine/commit/7dfbdb43584b0ee71bc14f936f2d4099a6dec01f#diff-f60041151ed3c0437580fc005ee1495656c4a4f8104e126e224c56d0f3fb59a8R187). But it has a lot of fixes. Since most of the traffic now has https, I recommend releasing patch 1.1.1, which will add check for https. It is impossible to open PR in the main branch, so I hang it as an issue.

Patch callback_helper.rb#L77:
```
if url.start_with?('https')
         http.use_ssl = true
         http.verify_mode = OpenSSL::SSL::VERIFY_NONE
end
```

**Comment by LinneyS** [comment]
Fixed #14

**Comment by VizzleTF** [comment]
Hello, it still doesn't work in main branch. I tried to uncomment callback_helper.rb#L77-80 - it doesnt work.
`[ERROR] nodeJS - error downloadFile:url=**http**://redmine.examp.le`

Can you help me make it work with https?
